language: node_js
node_js: 16
cache: npm
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: "chatkitty"
  skip_cleanup: true
  local_dir: "lib"
  upload-dir: "dist/react-component-library"
